import React from "react";
import type { MasterPredictionResult } from "../../core/MasterPredictionEngine";
import { GokarnaKundaliTemplate } from "../template/GokarnaKundaliTemplate";
import type { KundliViewerSession } from "../../stores/kundliViewerStore";
import { calculateTraditionalBaggona } from "../../core/TraditionalBaggonaEngine";
import { format } from "date-fns";
import { useTranslation } from "react-i18next";
import { stripJayashreeIntro } from "../../features/premiumPdf/premiumPdfLocale";
import { generatePanchangaAngaSynthesis } from "../../core/PanchangaAngaSynthesisEngine";

interface PremiumPDFTemplateProps {
  prediction: MasterPredictionResult;
  lang?: string;
  session?: KundliViewerSession | null;
  /** Person's current age in decimal years. When <= 12, the Niguda (Dark Secret) section is omitted. */
  ageYears?: number;
}

export const PremiumPDFTemplate: React.FC<PremiumPDFTemplateProps> = ({ prediction, lang = "en", session, ageYears }) => {
  // Children (age <= 12) do not receive the Niguda Rahasya (Dark Secret) section
  const isChild = typeof ageYears === "number" && ageYears <= 12;
  const { t: translate } = useTranslation();
  const isKn = lang.startsWith("kn");
  const langKey = (lang || "en").split("-")[0];

  const I18N_PREMIUM_PDF: Record<string, Record<string, string>> = {
    kn: {
      bookOfDestiny: "ವಿಧಿಯ ಪುಸ್ತಕ",
      title: "ನಕ್ಷತ್ರಗಳ ಮಾರ್ಗ",
      recordFor: "ವೈಯಕ್ತಿಕ ಜ್ಯೋತಿಷ್ಯ ವರದಿ:",
      subtitle: "ಸಮಗ್ರ ಜ್ಯೋತಿಷ್ಯ ವಿಶ್ಲೇಷಣೆ",
      calculatedFor: "ಜನನ ವಿವರಗಳ ಆಧಾರದ ಮೇಲೆ ರಚಿಸಲಾಗಿದೆ:",
      dob: "ಜನನ ದಿನಾಂಕ",
      time: "ಸಮಯ",
      generatedBy: "ಭಾಗ್ಗೋಣ ಪಂಚಾಂಗ ಜ್ಯೋತಿಷ್ಯದಿಂದ ರಚಿಸಲಾಗಿದೆ",
      chapter: "ಅಧ್ಯಾಯ",
      characteristicsTitle: "ವ್ಯಕ್ತಿತ್ವದ ಗುಣಲಕ್ಷಣಗಳು",
      darkSecretTitle: "ನಿಗೂಢ ಸತ್ಯ",
      currentPhase: "ಪ್ರಸ್ತುತ ಮನಸ್ಥಿತಿ ಮತ್ತು ಜೀವನ",
      next6Months: "ಮುಂದಿನ 6-12 ತಿಂಗಳ ಭವಿಷ್ಯ",
      bhavishya: "ಭವಿಷ್ಯ (ಜೀವನದ ವಿವಿಧ ಆಯಾಮಗಳು)",
      health: "ಆರೋಗ್ಯ",
      marriage: "ಮದುವೆ ಮತ್ತು ಸಂಬಂಧ",
      children: "ಮಕ್ಕಳು ಮತ್ತು ಸಂತತಿ",
      career: "ಉದ್ಯೋಗ",
      wealth: "ಕುಟುಂಬ ಮತ್ತು ಸಂಪತ್ತು",
      yogasTitle: "ಯೋಗಗಳು",
      doshasTitle: "ದೋಷಗಳು",
      cycleOfTime: "ಮುಂದಿನ 12 ತಿಂಗಳ ಯೋಜನೆ",
      summary: "ಸಾರಾಂಶ",
      ashirvadaTitle: "ಜ್ಯೋತಿಷಿಯ ಆಶೀರ್ವಾದ",
      impact: "ವಿವರಣೆ:",
      remedy: "ಪರಿಹಾರ:",
      endOfReading: "ಓದುವಿಕೆ ಮುಕ್ತಾಯ",
      luckyVehicles: "ಅದೃಷ್ಟ ವಾಹನ ಬಣ್ಣಗಳು & ದಿಕ್ಕುಗಳು:",
      carColors: "ಅದೃಷ್ಟ ವಾಹನ ಬಣ್ಣ:",
      clothColors: "ಅದೃಷ್ಟ ವಸ್ತ್ರ ಬಣ್ಣ:",
      avoidColors: "ವರ್ಜಿಸಬೇಕಾದ ಬಣ್ಣ:",
      luckyDirections: "ಅದೃಷ್ಟ ದಿಕ್ಕು & ಸಂಖ್ಯೆಗಳು:",
      numbersLabel: "ಸಂಖ್ಯೆಗಳು:"
    },
    en: {
      bookOfDestiny: "Book of Destiny",
      title: "The Path\nof the Stars",
      recordFor: "A PERSONALIZED ASTROLOGICAL RECORD FOR",
      subtitle: "A Comprehensive Astrological Analysis",
      calculatedFor: "Calculated for the precise birth details of:",
      dob: "DOB",
      time: "Time",
      generatedBy: "Generated by Baggona Panchanga Astrology",
      chapter: "Chapter",
      characteristicsTitle: "Characteristics of the Person",
      darkSecretTitle: "The Dark Secret",
      currentPhase: "Current Life Phase",
      next6Months: "Next 6 to 12 Months Prediction",
      bhavishya: "Bhavishya (Life Areas)",
      health: "Health",
      marriage: "Marriage & Relationships",
      children: "Children & Progeny",
      career: "Career",
      wealth: "Wealth & Family",
      yogasTitle: "Yogas",
      doshasTitle: "Doshas",
      cycleOfTime: "Next 12 Months Plan",
      summary: "Summary",
      ashirvadaTitle: "Astrologer's Blessing",
      impact: "Details:",
      remedy: "Remedy:",
      endOfReading: "End of Reading",
      luckyVehicles: "Lucky Vehicle Colors & Directions:",
      carColors: "Car/Bike Colors:",
      clothColors: "Garment Colors:",
      avoidColors: "Colors to Avoid:",
      luckyDirections: "Lucky Directions & Numbers:",
      numbersLabel: "Numbers:"
    },
    hi: {
      bookOfDestiny: "भाग्य की पुस्तक",
      title: "नक्षत्रों का मार्ग",
      recordFor: "व्यक्तिगत ज्योतिषीय प्रतिवेदन:",
      subtitle: "समग्र ज्योतिषीय विश्लेषण",
      calculatedFor: "सटीक जन्म विवरण के आधार पर निर्मित:",
      dob: "जन्म तिथि",
      time: "समय",
      generatedBy: "बग्गोण पंचांग ज्योतिष द्वारा निर्मित",
      chapter: "अध्याय",
      characteristicsTitle: "व्यक्तित्व के लक्षण",
      darkSecretTitle: "निगूढ़ रहस्य",
      currentPhase: "वर्तमान जीवन चरण",
      next6Months: "आगामी ६-१२ महीनों का भविष्यफल",
      bhavishya: "भविष्य (जीवन के विविध आयाम)",
      health: "स्वास्थ्य",
      marriage: "विवाह एवं संबंध",
      children: "संतान एवं संतति",
      career: "आजीविका एवं व्यवसाय",
      wealth: "परिवार एवं संपत्ति",
      yogasTitle: "शुभ योग",
      doshasTitle: "दोष विश्लेषण",
      cycleOfTime: "आगामी १२ महीनों की कार्ययोजना",
      summary: "सारांश",
      ashirvadaTitle: "ज्योतिषी का आशीर्वाद",
      impact: "विवरण:",
      remedy: "उपाय:",
      endOfReading: "वाचन समाप्त",
      luckyVehicles: "शुभ वाहन रंग एवं दिशाएं:",
      carColors: "शुभ वाहन रंग:",
      clothColors: "शुभ वस्त्र रंग:",
      avoidColors: "त्याज्य रंग:",
      luckyDirections: "शुभ दिशा एवं अंक:",
      numbersLabel: "अंक:"
    },
    te: {
      bookOfDestiny: "విధి గ్రంథం",
      title: "నక్షత్రాల మార్గం",
      recordFor: "వ్యక్తిగత జ్యోతిష్య నివేదిక:",
      subtitle: "సమగ్ర జ్యోతిష్య విశ్లేషణ",
      calculatedFor: "ఖచ్చితమైన జన్మ వివరాల ఆధారంగా రూపొందించబడింది:",
      dob: "జనన తేదీ",
      time: "సమయం",
      generatedBy: "బగ్గోణ పంచాంగ జ్యోతిష్యం ద్వారా రూపొందించబడింది",
      chapter: "అధ్యాయం",
      characteristicsTitle: "వ్యక్తిత్వ లక్షణాలు",
      darkSecretTitle: "నిగూఢ రహస్యం",
      currentPhase: "ప్రస్తుత జీవిత దశ",
      next6Months: "రాబోయే 6-12 నెలల భవిష్యత్తు",
      bhavishya: "భవిష్యత్తు (జీవిత రంగాలు)",
      health: "ఆరోగ్యం",
      marriage: "వివాహం మరియు సంబంధాలు",
      children: "సంతానం",
      career: "ఉద్యోగం మరియు వ్యాపారం",
      wealth: "సంపద మరియు కుటుంబం",
      yogasTitle: "యోగములు",
      doshasTitle: "దోషాలు",
      cycleOfTime: "రాబోయే 12 నెలల కార్యాచరణ",
      summary: "సారాంశం",
      ashirvadaTitle: "జ్యోతిష్యుల ఆశీర్వచనం",
      impact: "వివరణ:",
      remedy: "పరిహారం:",
      endOfReading: "పఠనం ముగింపు",
      luckyVehicles: "లక్కీ వాహన రంగులు & దిశలు:",
      carColors: "శుభ వాహన రంగు:",
      clothColors: "శుభ వస్త్ర రంగు:",
      avoidColors: "నివారించాల్సిన రంగులు:",
      luckyDirections: "శుభ దిశ & సంఖ్యలు:",
      numbersLabel: "సంఖ్యలు:"
    },
    ta: {
      bookOfDestiny: "விதியின் நூல்",
      title: "நட்சத்திரங்களின் பாதை",
      recordFor: "தனிப்பயனாக்கப்பட்ட ஜோதிட அறிக்கை:",
      subtitle: "முழுமையான ஜோதிட ஆய்வு",
      calculatedFor: "துல்லியமான பிறப்பு விவரங்களின்படி கணிக்கப்பட்டது:",
      dob: "பிறந்த தேதி",
      time: "நேரம்",
      generatedBy: "பக்கோன பஞ்சாங்க ஜோதிடத்தால் உருவாக்கப்பட்டது",
      chapter: "அத்தியாயம்",
      characteristicsTitle: "சுய குணாதிசயங்கள்",
      darkSecretTitle: "மறைமுக ரகசியம்",
      currentPhase: "தற்போதைய வாழ்க்கை நிலை",
      next6Months: "அடுத்த 6-12 மாதங்களுக்கான பலன்",
      bhavishya: "வாழ்க்கை வழிகாட்டுதல் (பல்வேறு நிலைகள்)",
      health: "ஆரோக்கியம்",
      marriage: "திருமணம் மற்றும் உறவுகள்",
      children: "குழந்தைப் பேறு",
      career: "தொழில் மற்றும் வேலைவாய்ப்பு",
      wealth: "குடும்பம் மற்றும் செல்வம்",
      yogasTitle: "சுப யோகங்கள்",
      doshasTitle: "தோஷங்கள்",
      cycleOfTime: "அடுத்த 12 மாத கால அட்டவணை",
      summary: "சுருக்கம்",
      ashirvadaTitle: "ஜோதிடரின் ஆசி",
      impact: "விவரம்:",
      remedy: "பரிகாரம்:",
      endOfReading: "வாசிப்பு நிறைவு",
      luckyVehicles: "அதிர்ஷ்ட வாகன நிறங்கள் & திசைகள்:",
      carColors: "சுப வாகன நிறம்:",
      clothColors: "சுப ஆடை நிறம்:",
      avoidColors: "தவிர்க்க வேண்டிய நிறங்கள்:",
      luckyDirections: "சுப திசை & எண்கள்:",
      numbersLabel: "எண்கள்:"
    }
  };

  const activeLang = I18N_PREMIUM_PDF[langKey] ? langKey : (isKn ? "kn" : "en");
  const t = I18N_PREMIUM_PDF[activeLang] || I18N_PREMIUM_PDF.en;

  const getFirstLetter = (text?: string) => text ? text.charAt(0) : "";
  const getRestOfText = (text?: string) => text ? text.substring(1) : "";

  const renderBhavishyaParagraph = (para: string, key: string) => {
    const trimmed = (para || "").trim();
    const isDoshaCallout = trimmed.startsWith("【") || trimmed.startsWith("[");
    if (isDoshaCallout) {
      return (
        <div
          key={key}
          style={{
            backgroundColor: "#fff1f2",
            borderLeft: "4px solid #e11d48",
            border: "1px solid #fecdd3",
            borderRadius: "6px",
            padding: "10px 14px",
            margin: "10px 0",
            fontSize: "13px",
            lineHeight: "1.65",
            color: "#881337"
          }}
        >
          <p style={{ margin: 0, fontWeight: 500 }}>{para}</p>
        </div>
      );
    }
    return <p key={key}>{para}</p>;
  };
  
  const narrative = prediction.aiGeneratedNarrative || {};
  
  const characteristics = narrative.characteristics || [];
  const darkSecret = narrative.darkSecret || [];
  const currentPhase = narrative.currentPhase || [];
  const next6Months = narrative.next6Months || [];
  const roadmap = narrative.roadmap || [];
  const bhavishya = narrative.bhavishya || {};
  const yogas = narrative.yogas || [];
  const doshas = narrative.doshas || [];
  const rawSummaryText = narrative.summary || "";
  const summaryText = stripJayashreeIntro(rawSummaryText);
  const ashirvadaText = narrative.ashirvada || "";

  // Panchanga 5-Angas Unified Prescriptions
  const targetKundli = session?.result || null;
  const synthesis = targetKundli ? generatePanchangaAngaSynthesis(targetKundli, {
    birthDate: prediction.metadata?.birthDate || session?.birthDateYmd || session?.input?.birthDate || "1990-01-01",
    birthTime: prediction.metadata?.birthTime || session?.birthTimeHm || session?.input?.birthTime || "12:00",
    latitude: session?.input?.latitude ?? 14.5479,
    longitude: session?.input?.longitude ?? 74.3187,
    lang
  }) : null;

  return (
    <div id="premium-pdf-container">
      <style>{`
        :root {
            --bg-color: #ffffff;
            --primary-dark: #0a1128;
            --text-main: #1a202c;
            --gold: #b79043;
            --gold-light: #fdfbf7;
        }

        #premium-pdf-container {
            font-family: 'Noto Serif', 'Noto Serif Kannada', serif;
            color: var(--text-main);
            background-color: #2d3748;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            line-height: 1.8;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 40px 0;
            word-wrap: break-word;
            overflow-wrap: break-word;
            word-break: break-word;
            hyphens: auto;
        }

        .pdf-page {
            width: 794px;
            min-height: 1123px;
            background-color: var(--bg-color);
            margin-bottom: 30px; 
            padding: 1.2in 0.85in;
            position: relative;
            box-shadow: -5px 0 15px rgba(0,0,0,0.2), 10px 0 20px rgba(0,0,0,0.1);
            page-break-after: always;
            page-break-inside: avoid;
            border-radius: 2px 5px 5px 2px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
        }

        @page { size: a4 portrait; margin: 0; }
        @media print {
            #premium-pdf-container { background-color: var(--bg-color); padding: 0; display: block; }
            .pdf-page { margin: 0; box-shadow: none; border-radius: 0; padding: 1.2in 0.85in; page-break-after: always; }
        }

        .pdf-page h1, .pdf-page h2, .pdf-page h3, .pdf-page .chapter-num {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            color: var(--text-main);
            text-align: center;
        }

        .pdf-page .chapter-num {
            font-size: 13pt;
            letter-spacing: 3px;
            color: var(--gold);
            text-transform: uppercase;
            margin-bottom: 15px;
            margin-top: 20px;
        }

        .pdf-page h2 {
            font-size: 26pt;
            font-weight: 600;
            margin-bottom: 45px;
            line-height: 1.3;
        }
        
        .pdf-page h3 {
            font-size: 16pt;
            margin-top: 30px;
            margin-bottom: 20px;
            text-transform: uppercase;
            letter-spacing: 1px;
            font-weight: 600;
            color: var(--primary-dark);
        }

        .pdf-page p {
            font-size: 13pt;
            text-align: justify;
            margin-bottom: 18px;
            text-indent: 1.5em;
        }

        .pdf-page p.first-paragraph {
            text-indent: 0;
        }

        .pdf-page .drop-cap {
            float: left;
            font-family: 'Cinzel', serif;
            font-size: 3.5em;
            line-height: 0.8;
            padding-right: 12px;
            padding-top: 8px;
            color: var(--gold);
        }

        .cover-page {
            background-color: var(--primary-dark);
            padding: 0.5in;
            color: white;
            justify-content: center;
            align-items: center;
        }

        .cover-border {
            border: 2px solid var(--gold);
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            padding: 60px 30px;
            position: relative;
        }

        .cover-border::before {
            content: '';
            position: absolute;
            top: 8px; left: 8px; right: 8px; bottom: 8px;
            border: 1px solid rgba(183, 144, 67, 0.4);
            pointer-events: none;
        }

        .book-title {
            font-size: 42pt;
            color: #ffffff;
            line-height: 1.3;
            margin: 30px 0;
            white-space: pre-wrap;
        }

        .title-page {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            height: 100%;
        }

        .tp-subtitle {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            font-size: 12pt;
            letter-spacing: 4px;
            color: var(--text-main);
            text-transform: uppercase;
            margin-bottom: 25px;
        }

        .tp-title {
            font-size: 34pt;
            margin-bottom: 50px;
            white-space: pre-wrap;
        }

        .tp-divider svg { width: 80px; fill: var(--gold); margin: 40px 0; }

        .yoga-entry { margin-top: 30px; }
        .yoga-entry p { text-indent: 0; margin-bottom: 12px; font-size: 12.5pt; }
        .yoga-name {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            font-size: 16pt;
            font-weight: bold;
            color: var(--text-main);
            display: block;
            margin-bottom: 10px;
            border-bottom: 1px solid rgba(0,0,0,0.1);
            padding-bottom: 5px;
        }

        .timeline-section { text-align: center; margin-top: 35px; }
        .timeline-month {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            font-size: 14pt;
            color: var(--gold);
            font-weight: bold;
            display: block;
            margin-bottom: 10px;
            text-transform: uppercase;
        }
        .timeline-section p { text-indent: 0; margin-bottom: 15px; font-size: 12.5pt; }

        .shloka-block { margin: 50px 10%; text-align: center; }
        .shloka-block p { text-indent: 0; text-align: center; }
        .shloka-text {
            font-size: 16pt;
            font-style: italic;
            font-weight: 600;
            margin-bottom: 20px !important;
            line-height: 1.8;
            color: var(--gold);
        }

        .chapter-end-mark { text-align: center; margin: 50px 0; }
        .chapter-end-mark svg { width: 50px; fill: var(--gold); }
      `}
      </style>

      {/* 0. KUNDLI CHART PAGE (Free PDF content) */}
      {session && session.result && (
        <div className="pdf-page" style={{ padding: 0, display: "flex", alignItems: "center", justifyContent: "center", backgroundColor: "#fbf8f1" }}>
          <div style={{ width: "100%", height: "100%" }}>
            <GokarnaKundaliTemplate
              kundli={session.result}
              personName={session.input.name || (isKn ? "ಜಾತಕರು" : activeLang === "hi" ? "जातक" : activeLang === "te" ? "జాతకుడు" : activeLang === "ta" ? "ஜாதகர்" : "Devotee")}
              parentsName={(session.input as any)?.parentsName || ""}
              birthDateObj={new Date(session.birthDateYmd)}
              birthTimeStr={session.birthTimeHm}
              isDayBirth={(() => {
                const hour = parseInt((session.birthTimeHm || "12:00").split(":")[0], 10);
                return !isNaN(hour) ? (hour >= 6 && hour < 18) : true;
              })()}
              panchanga={calculateTraditionalBaggona(session.birthDateYmd, session.birthTimeHm, session.input.latitude, session.input.longitude)}
              gothra={session.input.gothra ? translate(`gotras.${session.input.gothra}`) : ""}
              pdfLanguage={lang}
            />
          </div>
        </div>
      )}

      {/* 1. COVER PAGE */}
      <div className="pdf-page cover-page">
          <div className="cover-border">
              <div style={{ textAlign: "center", marginTop: "30px" }}>
                  <svg viewBox="0 0 100 100" style={{ width: "60px", fill: "var(--gold)", marginBottom: "20px" }}>
                      <path d="M50 0 L55 40 L95 50 L55 60 L50 100 L45 60 L5 50 L45 40 Z"/>
                  </svg>
                  <p style={{ textIndent: 0, fontFamily: "'Cinzel', serif", color: "var(--gold)", letterSpacing: "3px", fontSize: "11pt" }}>{t.bookOfDestiny}</p>
              </div>

              <h1 className="book-title">{t.title}</h1>
              
              <div style={{ textAlign: "center", marginBottom: "30px" }}>
                  <p style={{ textIndent: 0, color: "#a0aec0", fontSize: "12pt", letterSpacing: "2px", marginBottom: "10px" }}>{t.recordFor}</p>
                  <p style={{ textIndent: 0, fontFamily: "'Cinzel', 'Noto Serif Kannada', serif", fontSize: "20pt", color: "white" }}>{prediction.metadata.name}</p>
              </div>
          </div>
      </div>

      {/* 2. INNER TITLE PAGE */}
      <div className="pdf-page">
          <div className="title-page">
              <h4 className="tp-subtitle">{t.subtitle}</h4>
              <h1 className="tp-title">{t.title}</h1>
              
              <div className="tp-divider">
                  <svg viewBox="0 0 100 20">
                      <circle cx="50" cy="10" r="4" />
                      <line x1="10" y1="10" x2="40" y2="10" stroke="var(--gold)" strokeWidth="1"/>
                      <line x1="60" y1="10" x2="90" y2="10" stroke="var(--gold)" strokeWidth="1"/>
                  </svg>
              </div>

              <p style={{ textIndent: 0, textAlign: "center", marginBottom: "10px", fontSize: "13pt" }}>{t.calculatedFor}</p>
              <p style={{ textIndent: 0, fontFamily: "'Cinzel', 'Noto Serif Kannada', serif", fontSize: "20pt", fontWeight: "bold", textAlign: "center", color: "var(--text-main)" }}>{prediction.metadata.name}</p>
              <p style={{ textIndent: 0, textAlign: "center", marginTop: "20px", fontSize: "12pt" }}>
                {t.dob}: {prediction.metadata.birthDate} &nbsp;|&nbsp; {t.time}: {prediction.metadata.birthTime}
              </p>

              <div style={{ marginTop: "auto" }}>
                  <p style={{ textIndent: 0, textAlign: "center", fontSize: "11pt", color: "var(--gold)", letterSpacing: "2px", textTransform: "uppercase" }}>{t.generatedBy}</p>
              </div>
          </div>
      </div>

      {/* CHAPTER I: Characteristics */}
      {characteristics.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} I</div>
            <h2>{t.characteristicsTitle}</h2>
            {characteristics.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>
                    {idx === 0 ? (
                        <>
                            <span className="drop-cap">{getFirstLetter(para)}</span>
                            {getRestOfText(para)}
                        </>
                    ) : (
                        para
                    )}
                </p>
            ))}
        </div>
      )}

      {/* CHAPTER II: Dark Secret (Niguda Rahasya) — hidden for children aged 12 and below */}
      {!isChild && darkSecret.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} II</div>
            <h2>{t.darkSecretTitle}</h2>
            {darkSecret.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>
                    {idx === 0 ? (
                        <>
                            <span className="drop-cap">{getFirstLetter(para)}</span>
                            {getRestOfText(para)}
                        </>
                    ) : (
                        para
                    )}
                </p>
            ))}
        </div>
      )}

      {/* CHAPTER III: Current Phase */}
      {currentPhase.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} III</div>
            <h2>{t.currentPhase}</h2>
            {currentPhase.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>{para}</p>
            ))}
        </div>
      )}

      {/* CHAPTER IV: Next 6-12 Months */}
      {next6Months.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} IV</div>
            <h2>{t.next6Months}</h2>
            {next6Months.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>{para}</p>
            ))}
        </div>
      )}

      {/* CHAPTER V: Bhavishya (Life Areas) */}
      {(bhavishya.health || bhavishya.marriage || bhavishya.children || bhavishya.career || bhavishya.wealth) && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} V</div>
            <h2>{t.bhavishya}</h2>
            
            {bhavishya.health && bhavishya.health.length > 0 && (
                <>
                    <h3>{t.health}</h3>
                    {bhavishya.health.map((para, idx) => renderBhavishyaParagraph(para, 'h'+idx))}
                </>
            )}
            
            {bhavishya.marriage && bhavishya.marriage.length > 0 && (
                <>
                    <h3>{t.marriage}</h3>
                    {bhavishya.marriage.map((para, idx) => renderBhavishyaParagraph(para, 'm'+idx))}
                </>
            )}
            
            {bhavishya.children && bhavishya.children.length > 0 && (
                <>
                    <h3>{t.children}</h3>
                    {bhavishya.children.map((para, idx) => renderBhavishyaParagraph(para, 'c'+idx))}
                </>
            )}

            {bhavishya.career && bhavishya.career.length > 0 && (
                <>
                    <h3>{t.career}</h3>
                    {bhavishya.career.map((para, idx) => renderBhavishyaParagraph(para, 'ca'+idx))}
                </>
            )}

            {bhavishya.wealth && bhavishya.wealth.length > 0 && (
                <>
                    <h3>{t.wealth}</h3>
                    {bhavishya.wealth.map((para, idx) => renderBhavishyaParagraph(para, 'w'+idx))}
                </>
            )}
        </div>
      )}

      {/* CHAPTER VI: Yogas */}
      {yogas.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} VI</div>
            <h2>{t.yogasTitle}</h2>

            {yogas.map((y: any, idx: number) => (
                <div className="yoga-entry" key={`yoga-${idx}`}>
                    <span className="yoga-name">{y.name}</span>
                    {Array.isArray(y.significance) ? y.significance.map((p: string, i: number) => <p key={i}>{p}</p>) : <p>{y.significance}</p>}
                </div>
            ))}
        </div>
      )}

      {/* CHAPTER VII: Doshas */}
      {doshas.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} VII</div>
            <h2>{t.doshasTitle}</h2>

            {doshas.map((d: any, idx: number) => (
                <div className="yoga-entry" key={`dosha-${idx}`}>
                    <span className="yoga-name">{d.name}</span>
                    {Array.isArray(d.significance) ? d.significance.map((p: string, i: number) => <p key={i}>{p}</p>) : <p>{d.significance}</p>}
                    {d.remedy && (
                        <p><span style={{fontWeight: "bold", color: "var(--primary-dark)"}}>{t.remedy}</span> {d.remedy}</p>
                    )}
                </div>
            ))}
        </div>
      )}

      {/* CHAPTER VIII: Cycle of Time (Roadmap) */}
      {roadmap.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} VIII</div>
            <h2>{t.cycleOfTime}</h2>
            
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "30px", marginTop: "30px" }}>
                {roadmap.map((m: any, idx: number) => (
                    <div className="timeline-section" key={idx}>
                        <span className="timeline-month">{m.month}</span>
                        <div style={{ marginBottom: "15px", fontSize: "11pt", fontWeight: "bold", 
                            color: m.status === "Excellent" || m.status === "Good" ? "#2f855a" : (m.status === "Challenging" ? "#c53030" : "var(--gold)")
                        }}>
                            {m.status}
                        </div>
                        <p>{m.prediction}</p>
                    </div>
                ))}
            </div>
        </div>
      )}

      {/* CHAPTER IX: Summary */}
      {summaryText && (
          <div className="pdf-page">
            <div className="chapter-num">{t.chapter} IX</div>
            <h2>{t.summary}</h2>
            <p className="first-paragraph">
                <span className="drop-cap">{getFirstLetter(summaryText)}</span>
                {getRestOfText(summaryText)}
            </p>
          </div>
      )}

      {/* CHAPTER X: Panchanga Prescriptions & Remedies */}
      {synthesis && (
        <div className="pdf-page">
          <div className="chapter-num">{t.chapter} X</div>
          <h2>{isKn ? "ಪಂಚಾಂಗ ಸಮಗ್ರ ರಕ್ಷಾ ಕವಚ & ಭಾಗ್ಯ ರತ್ನ" : activeLang === "hi" ? "पंचांग समग्र रक्षा कवच एवं भाग्य रत्न" : activeLang === "te" ? "పంచాంగ సమగ్ర రక్షా కవచం & భాగ్య రత్నం" : activeLang === "ta" ? "பஞ்சாங்க பாதுகாப்பு கவசம் & அதிர்ஷ்ட ரத்தினம்" : "Panchanga Prescriptions & Sacred Armor"}</h2>
          
          <div style={{ marginTop: "20px" }}>
            <div className="yoga-entry" style={{ marginBottom: "25px", borderLeft: "4px solid var(--gold)", paddingLeft: "15px" }}>
              <span className="yoga-name" style={{ fontSize: "14pt", color: "var(--gold)" }}>
                📿 {isKn ? "ಶಿಫಾರಸು ಮಾಡಿದ ರುದ್ರಾಕ್ಷಿ:" : activeLang === "hi" ? "अनुशंसित रुद्राक्ष:" : activeLang === "te" ? "సిఫార్సు చేయబడిన రుద్రాక్ష:" : activeLang === "ta" ? "பரிந்துரைக்கப்பட்ட ருத்ராட்சம்:" : "Prescribed Rudraksha:"} {synthesis.prescriptions.rudraksha.nameKn}
              </span>
              <p style={{ textIndent: 0, marginTop: "8px" }}>
                <b>{isKn ? "ಅಧಿಪತಿ ದೇವತೆ:" : activeLang === "hi" ? "अधिपति देवता:" : activeLang === "te" ? "అధిపతి దేవత:" : activeLang === "ta" ? "அதிபதி தெய்வம்:" : "Ruling Deity:"}</b> {synthesis.prescriptions.rudraksha.deity} • <b>{isKn ? "ಗ್ರಹ:" : activeLang === "hi" ? "ग्रह:" : activeLang === "te" ? "గ్రహం:" : activeLang === "ta" ? "கிரகம்:" : "Planet:"}</b> {synthesis.prescriptions.rudraksha.planet}
              </p>
              <p style={{ textIndent: 0 }}>
                <b>{isKn ? "ಶಾಸ್ತ್ರೀಯ ಕಾರಣ:" : activeLang === "hi" ? "शास्त्रीय कारण:" : activeLang === "te" ? "శాస్త్రీయ కారణం:" : activeLang === "ta" ? "சாஸ்திர காரணம்:" : "Astrological Reason:"}</b> {synthesis.prescriptions.rudraksha.astrologicalReason}
              </p>
              <p style={{ textIndent: 0, fontSize: "11pt", color: "#2f855a" }}>
                ✨ <b>{isKn ? "ಪಂಚಾಂಗ ಸಮನ್ವಯ:" : activeLang === "hi" ? "पंचांग समन्वय:" : activeLang === "te" ? "పంచాంగ సమన్వయం:" : activeLang === "ta" ? "பஞ்சாங்க ஒருங்கிணைப்பு:" : "Panchanga Synergy:"}</b> {synthesis.prescriptions.rudraksha.panchangaSynergy}
              </p>
              <p style={{ textIndent: 0, fontSize: "11pt", color: "#4a5568" }}>
                <b>{isKn ? "ಧರಿಸುವ ವಿಧಾನ:" : activeLang === "hi" ? "धारण विधि:" : activeLang === "te" ? "ధారణ విధానం:" : activeLang === "ta" ? "அணியும் முறை:" : "Wearing Method:"}</b> {synthesis.prescriptions.rudraksha.wearingMethod}
              </p>
            </div>

            <div className="yoga-entry" style={{ marginBottom: "25px", borderLeft: "4px solid var(--gold)", paddingLeft: "15px" }}>
              <span className="yoga-name" style={{ fontSize: "14pt", color: "var(--gold)" }}>
                💍 {isKn ? "ಭಾಗ್ಯ ರತ್ನ ಉಂಗುರ:" : activeLang === "hi" ? "भाग्य रत्न अंगूठी:" : activeLang === "te" ? "భాగ్య రత్న ఉంగరం:" : activeLang === "ta" ? "அதிர்ஷ்ட ரத்தின மோதிரம்:" : "Prescribed Gemstone Ring:"} {synthesis.prescriptions.gemstoneRing.primaryGemstoneKn}
              </span>
              <p style={{ textIndent: 0, marginTop: "8px" }}>
                <b>{isKn ? "ತೂಕ & ಲೋಹ:" : activeLang === "hi" ? "भार एवं धातु:" : activeLang === "te" ? "బరువు & లోహం:" : activeLang === "ta" ? "எடை & உலோகம்:" : "Weight & Metal:"}</b> {synthesis.prescriptions.gemstoneRing.caratWeight} • {synthesis.prescriptions.gemstoneRing.metalKn}
              </p>
              <p style={{ textIndent: 0 }}>
                <b>{isKn ? "ಬೆರಳು & ಶುಭ ಕಾಲ:" : activeLang === "hi" ? "अंगुली एवं शुभ दिन:" : activeLang === "te" ? "వేలు & శుభ దినం:" : activeLang === "ta" ? "விரல் & சுப நாள்:" : "Finger & Day:"}</b> {synthesis.prescriptions.gemstoneRing.fingerKn} ({synthesis.prescriptions.gemstoneRing.activationDay})
              </p>
              <p style={{ textIndent: 0 }}>
                <b>{isKn ? "ಶಾಸ್ತ್ರೀಯ ಕಾರಣ:" : activeLang === "hi" ? "शास्त्रीय कारण:" : activeLang === "te" ? "శాస్త్రీయ కారణం:" : activeLang === "ta" ? "சாஸ்திர காரணம்:" : "Astrological Reason:"}</b> {synthesis.prescriptions.gemstoneRing.astrologicalReason}
              </p>
              <p style={{ textIndent: 0, fontSize: "11pt", color: "#2f855a" }}>
                ✨ <b>{isKn ? "ಪಂಚಾಂಗ ಸಮನ್ವಯ:" : activeLang === "hi" ? "पंचांग समन्वय:" : activeLang === "te" ? "పంచాంగ సమన్వయం:" : activeLang === "ta" ? "பஞ்சாங்க ஒருங்கிணைப்பு:" : "Panchanga Synergy:"}</b> {synthesis.prescriptions.gemstoneRing.panchangaSynergy}
              </p>
            </div>

            <div style={{ background: "var(--gold-light)", padding: "15px 20px", borderRadius: "8px", border: "1px solid rgba(183, 144, 67, 0.3)", marginTop: "20px" }}>
              <h3 style={{ fontSize: "12pt", margin: "0 0 10px 0", color: "var(--primary-dark)" }}>
                🚗 {t.luckyVehicles}
              </h3>
              <p style={{ textIndent: 0, fontSize: "11pt", margin: "0 0 6px 0" }}>
                <b>{t.carColors}</b> {synthesis.prescriptions.luckyAttributes.carColors.join(", ")}
              </p>
              <p style={{ textIndent: 0, fontSize: "11pt", margin: "0 0 6px 0" }}>
                <b>{t.clothColors}</b> {synthesis.prescriptions.luckyAttributes.clothColors.join(", ")}
              </p>
              <p style={{ textIndent: 0, fontSize: "11pt", margin: "0 0 6px 0", color: "#c53030" }}>
                <b>{t.avoidColors}</b> {synthesis.prescriptions.luckyAttributes.avoidColors.join(", ")}
              </p>
              <p style={{ textIndent: 0, fontSize: "11pt", margin: 0, color: "var(--gold)" }}>
                <b>{t.luckyDirections}</b> {synthesis.prescriptions.luckyAttributes.directions.join(", ")} ({t.numbersLabel} {synthesis.prescriptions.luckyAttributes.numbers.join(", ")})
              </p>
            </div>
          </div>
        </div>
      )}

      {/* END OF READING MARKER */}
      <div className="pdf-page" style={{ justifyContent: "center", alignItems: "center", minHeight: "400px" }}>
          <div className="shloka-block">
              <p className="shloka-text">{prediction.shloka.sanskrit}</p>
              <p style={{ fontSize: "12pt" }}>"{prediction.shloka.meaning}"</p>
          </div>

          {ashirvadaText && (
              <div style={{ marginTop: "40px", textAlign: "center", padding: "0 40px" }}>
                  <div style={{ fontSize: "42pt", color: "var(--gold)", marginBottom: "20px", fontFamily: "'Noto Sans Devanagari', serif", opacity: 0.9 }}>ॐ</div>
                  <h3 style={{ fontSize: "20pt", fontStyle: "italic", marginBottom: "20px", color: "var(--primary-dark)" }}>{t.ashirvadaTitle}</h3>
                  <p style={{ fontSize: "14pt", fontStyle: "italic", textAlign: "center", textIndent: 0, lineHeight: 1.8 }}>
                      "{ashirvadaText}"
                  </p>
              </div>
          )}
          
          <div style={{ textAlign: "center", marginTop: "80px", borderTop: "1px solid var(--gold)", paddingTop: "40px", width: "50%" }}>
              <p style={{ textIndent: 0, fontFamily: "'Cinzel', 'Noto Serif Kannada', serif", letterSpacing: "2px", textTransform: "uppercase", fontSize: "14pt", color: "var(--primary-dark)" }}>
                  {t.endOfReading}
              </p>
          </div>
      </div>

    </div>
  );
};
