import React from "react";
import type { MasterPredictionResult } from "../../core/MasterPredictionEngine";
import { GokarnaKundaliTemplate } from "../template/GokarnaKundaliTemplate";
import type { KundliViewerSession } from "../../stores/kundliViewerStore";
import { calculateTraditionalBaggona } from "../../core/TraditionalBaggonaEngine";
import { format } from "date-fns";
import { useTranslation } from "react-i18next";
import { stripJayashreeIntro } from "../../features/premiumPdf/premiumPdfLocale";

interface PremiumPDFTemplateProps {
  prediction: MasterPredictionResult;
  lang?: string;
  session?: KundliViewerSession | null;
  /** Person's current age in decimal years. When <= 12, the Niguda (Dark Secret) section is omitted. */
  ageYears?: number;
}

export const PremiumPDFTemplate: React.FC<PremiumPDFTemplateProps> = ({ prediction, lang = "en", session, ageYears }) => {
  // Children (age <= 12) do not receive the Niguda Rahasya (Dark Secret) section
  const isChild = typeof ageYears === "number" && ageYears <= 12;
  const { t: translate } = useTranslation();
  const isKn = lang.startsWith("kn");

  const t = {
    bookOfDestiny: isKn ? "ವಿಧಿಯ ಪುಸ್ತಕ" : "Book of Destiny",
    title: isKn ? "ನಕ್ಷತ್ರಗಳ ಮಾರ್ಗ" : "The Path\nof the Stars",
    recordFor: isKn ? "ವೈಯಕ್ತಿಕ ಜ್ಯೋತಿಷ್ಯ ವರದಿ:" : "A PERSONALIZED ASTROLOGICAL RECORD FOR",
    subtitle: isKn ? "ಸಮಗ್ರ ಜ್ಯೋತಿಷ್ಯ ವಿಶ್ಲೇಷಣೆ" : "A Comprehensive Astrological Analysis",
    calculatedFor: isKn ? "ಜನನ ವಿವರಗಳ ಆಧಾರದ ಮೇಲೆ ರಚಿಸಲಾಗಿದೆ:" : "Calculated for the precise birth details of:",
    dob: isKn ? "ಜನನ ದಿನಾಂಕ" : "DOB",
    time: isKn ? "ಸಮಯ" : "Time",
    generatedBy: isKn ? "ಭಾಗ್ಗೋಣ ಪಂಚಾಂಗ ಜ್ಯೋತಿಷ್ಯದಿಂದ ರಚಿಸಲಾಗಿದೆ" : "Generated by Baggona Panchanga Astrology",
    chapter: isKn ? "ಅಧ್ಯಾಯ" : "Chapter",
    characteristicsTitle: isKn ? "ವ್ಯಕ್ತಿತ್ವದ ಗುಣಲಕ್ಷಣಗಳು" : "Characteristics of the Person",
    darkSecretTitle: isKn ? "ನಿಗೂಢ ಸತ್ಯ" : "The Dark Secret",
    currentPhase: isKn ? "ಪ್ರಸ್ತುತ ಮನಸ್ಥಿತಿ ಮತ್ತು ಜೀವನ" : "Current Life Phase",
    next6Months: isKn ? "ಮುಂದಿನ 6-12 ತಿಂಗಳ ಭವಿಷ್ಯ" : "Next 6 to 12 Months Prediction",
    bhavishya: isKn ? "ಭವಿಷ್ಯ (ಜೀವನದ ವಿವಿಧ ಆಯಾಮಗಳು)" : "Bhavishya (Life Areas)",
    health: isKn ? "ಆರೋಗ್ಯ" : "Health",
    marriage: isKn ? "ಮದುವೆ ಮತ್ತು ಸಂಬಂಧ" : "Marriage & Relationships",
    children: isKn ? "ಮಕ್ಕಳು ಮತ್ತು ಸಂತತಿ" : "Children & Progeny",
    career: isKn ? "ಉದ್ಯೋಗ" : "Career",
    wealth: isKn ? "ಕುಟುಂಬ ಮತ್ತು ಸಂಪತ್ತು" : "Wealth & Family",
    yogasTitle: isKn ? "ಯೋಗಗಳು" : "Yogas",
    doshasTitle: isKn ? "ದೋಷಗಳು" : "Doshas",
    cycleOfTime: isKn ? "ಮುಂದಿನ 12 ತಿಂಗಳ ಯೋಜನೆ" : "Next 12 Months Plan",
    summary: isKn ? "ಸಾರಾಂಶ" : "Summary",
    ashirvadaTitle: isKn ? "ಜ್ಯೋತಿಷಿಯ ಆಶೀರ್ವಾದ" : "Astrologer's Blessing",
    impact: isKn ? "ವಿವರಣೆ:" : "Details:",
    remedy: isKn ? "ಪರಿಹಾರ:" : "Remedy:",
    endOfReading: isKn ? "ಓದುವಿಕೆ ಮುಕ್ತಾಯ" : "End of Reading"
  };

  const getFirstLetter = (text?: string) => text ? text.charAt(0) : "";
  const getRestOfText = (text?: string) => text ? text.substring(1) : "";
  
  const narrative = prediction.aiGeneratedNarrative || {};
  
  const characteristics = narrative.characteristics || [];
  const darkSecret = narrative.darkSecret || [];
  const currentPhase = narrative.currentPhase || [];
  const next6Months = narrative.next6Months || [];
  const roadmap = narrative.roadmap || [];
  const bhavishya = narrative.bhavishya || {};
  const yogas = narrative.yogas || [];
  const doshas = narrative.doshas || [];
  const rawSummaryText = narrative.summary || "";
  const summaryText = stripJayashreeIntro(rawSummaryText);
  const ashirvadaText = narrative.ashirvada || "";

  return (
    <div id="premium-pdf-container">
      <style>{`
        :root {
            --bg-color: #ffffff;
            --primary-dark: #0a1128;
            --text-main: #1a202c;
            --gold: #b79043;
            --gold-light: #fdfbf7;
        }

        #premium-pdf-container {
            font-family: 'Noto Serif', 'Noto Serif Kannada', serif;
            color: var(--text-main);
            background-color: #2d3748;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            line-height: 1.8;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 40px 0;
            word-wrap: break-word;
            overflow-wrap: break-word;
            word-break: break-word;
            hyphens: auto;
        }

        .pdf-page {
            width: 794px;
            min-height: 1123px;
            background-color: var(--bg-color);
            margin-bottom: 30px; 
            padding: 1.2in 0.85in;
            position: relative;
            box-shadow: -5px 0 15px rgba(0,0,0,0.2), 10px 0 20px rgba(0,0,0,0.1);
            page-break-after: always;
            page-break-inside: avoid;
            border-radius: 2px 5px 5px 2px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
        }

        @page { size: a4 portrait; margin: 0; }
        @media print {
            #premium-pdf-container { background-color: var(--bg-color); padding: 0; display: block; }
            .pdf-page { margin: 0; box-shadow: none; border-radius: 0; padding: 1.2in 0.85in; page-break-after: always; }
        }

        .pdf-page h1, .pdf-page h2, .pdf-page h3, .pdf-page .chapter-num {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            color: var(--text-main);
            text-align: center;
        }

        .pdf-page .chapter-num {
            font-size: 13pt;
            letter-spacing: 3px;
            color: var(--gold);
            text-transform: uppercase;
            margin-bottom: 15px;
            margin-top: 20px;
        }

        .pdf-page h2 {
            font-size: 26pt;
            font-weight: 600;
            margin-bottom: 45px;
            line-height: 1.3;
        }
        
        .pdf-page h3 {
            font-size: 16pt;
            margin-top: 30px;
            margin-bottom: 20px;
            text-transform: uppercase;
            letter-spacing: 1px;
            font-weight: 600;
            color: var(--primary-dark);
        }

        .pdf-page p {
            font-size: 13pt;
            text-align: justify;
            margin-bottom: 18px;
            text-indent: 1.5em;
        }

        .pdf-page p.first-paragraph {
            text-indent: 0;
        }

        .pdf-page .drop-cap {
            float: left;
            font-family: 'Cinzel', serif;
            font-size: 3.5em;
            line-height: 0.8;
            padding-right: 12px;
            padding-top: 8px;
            color: var(--gold);
        }

        .cover-page {
            background-color: var(--primary-dark);
            padding: 0.5in;
            color: white;
            justify-content: center;
            align-items: center;
        }

        .cover-border {
            border: 2px solid var(--gold);
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            padding: 60px 30px;
            position: relative;
        }

        .cover-border::before {
            content: '';
            position: absolute;
            top: 8px; left: 8px; right: 8px; bottom: 8px;
            border: 1px solid rgba(183, 144, 67, 0.4);
            pointer-events: none;
        }

        .book-title {
            font-size: 42pt;
            color: #ffffff;
            line-height: 1.3;
            margin: 30px 0;
            white-space: pre-wrap;
        }

        .title-page {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            height: 100%;
        }

        .tp-subtitle {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            font-size: 12pt;
            letter-spacing: 4px;
            color: var(--text-main);
            text-transform: uppercase;
            margin-bottom: 25px;
        }

        .tp-title {
            font-size: 34pt;
            margin-bottom: 50px;
            white-space: pre-wrap;
        }

        .tp-divider svg { width: 80px; fill: var(--gold); margin: 40px 0; }

        .yoga-entry { margin-top: 30px; }
        .yoga-entry p { text-indent: 0; margin-bottom: 12px; font-size: 12.5pt; }
        .yoga-name {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            font-size: 16pt;
            font-weight: bold;
            color: var(--text-main);
            display: block;
            margin-bottom: 10px;
            border-bottom: 1px solid rgba(0,0,0,0.1);
            padding-bottom: 5px;
        }

        .timeline-section { text-align: center; margin-top: 35px; }
        .timeline-month {
            font-family: 'Cinzel', 'Noto Serif Kannada', serif;
            font-size: 14pt;
            color: var(--gold);
            font-weight: bold;
            display: block;
            margin-bottom: 10px;
            text-transform: uppercase;
        }
        .timeline-section p { text-indent: 0; margin-bottom: 15px; font-size: 12.5pt; }

        .shloka-block { margin: 50px 10%; text-align: center; }
        .shloka-block p { text-indent: 0; text-align: center; }
        .shloka-text {
            font-size: 16pt;
            font-style: italic;
            font-weight: 600;
            margin-bottom: 20px !important;
            line-height: 1.8;
            color: var(--gold);
        }

        .chapter-end-mark { text-align: center; margin: 50px 0; }
        .chapter-end-mark svg { width: 50px; fill: var(--gold); }
      `}
      </style>

      {/* 0. KUNDLI CHART PAGE (Free PDF content) */}
      {session && session.result && (
        <div className="pdf-page" style={{ padding: 0, display: "flex", alignItems: "center", justifyContent: "center", backgroundColor: "#fbf8f1" }}>
          <div style={{ width: "100%", height: "100%" }}>
            <GokarnaKundaliTemplate
              kundli={session.result}
              personName={session.input.name || "Seeker"}
              parentsName={""}
              birthDateObj={new Date(session.birthDateYmd)}
              birthTimeStr={session.birthTimeHm}
              isDayBirth={true}
              panchanga={calculateTraditionalBaggona(session.birthDateYmd, session.birthTimeHm, session.input.latitude, session.input.longitude)}
              gothra={session.input.gothra ? translate(`gotras.${session.input.gothra}`) : ""}
            />
          </div>
        </div>
      )}

      {/* 1. COVER PAGE */}
      <div className="pdf-page cover-page">
          <div className="cover-border">
              <div style={{ textAlign: "center", marginTop: "30px" }}>
                  <svg viewBox="0 0 100 100" style={{ width: "60px", fill: "var(--gold)", marginBottom: "20px" }}>
                      <path d="M50 0 L55 40 L95 50 L55 60 L50 100 L45 60 L5 50 L45 40 Z"/>
                  </svg>
                  <p style={{ textIndent: 0, fontFamily: "'Cinzel', serif", color: "var(--gold)", letterSpacing: "3px", fontSize: "11pt" }}>{t.bookOfDestiny}</p>
              </div>

              <h1 className="book-title">{t.title}</h1>
              
              <div style={{ textAlign: "center", marginBottom: "30px" }}>
                  <p style={{ textIndent: 0, color: "#a0aec0", fontSize: "12pt", letterSpacing: "2px", marginBottom: "10px" }}>{t.recordFor}</p>
                  <p style={{ textIndent: 0, fontFamily: "'Cinzel', 'Noto Serif Kannada', serif", fontSize: "20pt", color: "white" }}>{prediction.metadata.name}</p>
              </div>
          </div>
      </div>

      {/* 2. INNER TITLE PAGE */}
      <div className="pdf-page">
          <div className="title-page">
              <h4 className="tp-subtitle">{t.subtitle}</h4>
              <h1 className="tp-title">{t.title}</h1>
              
              <div className="tp-divider">
                  <svg viewBox="0 0 100 20">
                      <circle cx="50" cy="10" r="4" />
                      <line x1="10" y1="10" x2="40" y2="10" stroke="var(--gold)" strokeWidth="1"/>
                      <line x1="60" y1="10" x2="90" y2="10" stroke="var(--gold)" strokeWidth="1"/>
                  </svg>
              </div>

              <p style={{ textIndent: 0, textAlign: "center", marginBottom: "10px", fontSize: "13pt" }}>{t.calculatedFor}</p>
              <p style={{ textIndent: 0, fontFamily: "'Cinzel', 'Noto Serif Kannada', serif", fontSize: "20pt", fontWeight: "bold", textAlign: "center", color: "var(--text-main)" }}>{prediction.metadata.name}</p>
              <p style={{ textIndent: 0, textAlign: "center", marginTop: "20px", fontSize: "12pt" }}>
                {t.dob}: {prediction.metadata.birthDate} &nbsp;|&nbsp; {t.time}: {prediction.metadata.birthTime}
              </p>

              <div style={{ marginTop: "auto" }}>
                  <p style={{ textIndent: 0, textAlign: "center", fontSize: "11pt", color: "var(--gold)", letterSpacing: "2px", textTransform: "uppercase" }}>{t.generatedBy}</p>
              </div>
          </div>
      </div>

      {/* CHAPTER I: Characteristics */}
      {characteristics.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} I</div>
            <h2>{t.characteristicsTitle}</h2>
            {characteristics.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>
                    {idx === 0 ? (
                        <>
                            <span className="drop-cap">{getFirstLetter(para)}</span>
                            {getRestOfText(para)}
                        </>
                    ) : (
                        para
                    )}
                </p>
            ))}
        </div>
      )}

      {/* CHAPTER II: Dark Secret (Niguda Rahasya) — hidden for children aged 12 and below */}
      {!isChild && darkSecret.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} II</div>
            <h2>{t.darkSecretTitle}</h2>
            {darkSecret.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>
                    {idx === 0 ? (
                        <>
                            <span className="drop-cap">{getFirstLetter(para)}</span>
                            {getRestOfText(para)}
                        </>
                    ) : (
                        para
                    )}
                </p>
            ))}
        </div>
      )}

      {/* CHAPTER III: Current Phase */}
      {currentPhase.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} III</div>
            <h2>{t.currentPhase}</h2>
            {currentPhase.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>{para}</p>
            ))}
        </div>
      )}

      {/* CHAPTER IV: Next 6-12 Months */}
      {next6Months.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} IV</div>
            <h2>{t.next6Months}</h2>
            {next6Months.map((para, idx) => (
                <p key={idx} className={idx === 0 ? "first-paragraph" : ""}>{para}</p>
            ))}
        </div>
      )}

      {/* CHAPTER V: Bhavishya (Life Areas) */}
      {(bhavishya.health || bhavishya.marriage || bhavishya.children || bhavishya.career || bhavishya.wealth) && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} V</div>
            <h2>{t.bhavishya}</h2>
            
            {bhavishya.health && bhavishya.health.length > 0 && (
                <>
                    <h3>{t.health}</h3>
                    {bhavishya.health.map((para, idx) => <p key={'h'+idx}>{para}</p>)}
                </>
            )}
            
            {bhavishya.marriage && bhavishya.marriage.length > 0 && (
                <>
                    <h3>{t.marriage}</h3>
                    {bhavishya.marriage.map((para, idx) => <p key={'m'+idx}>{para}</p>)}
                </>
            )}
            
            {bhavishya.children && bhavishya.children.length > 0 && (
                <>
                    <h3>{t.children}</h3>
                    {bhavishya.children.map((para, idx) => <p key={'c'+idx}>{para}</p>)}
                </>
            )}

            {bhavishya.career && bhavishya.career.length > 0 && (
                <>
                    <h3>{t.career}</h3>
                    {bhavishya.career.map((para, idx) => <p key={'ca'+idx}>{para}</p>)}
                </>
            )}

            {bhavishya.wealth && bhavishya.wealth.length > 0 && (
                <>
                    <h3>{t.wealth}</h3>
                    {bhavishya.wealth.map((para, idx) => <p key={'w'+idx}>{para}</p>)}
                </>
            )}
        </div>
      )}

      {/* CHAPTER VI: Yogas */}
      {yogas.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} VI</div>
            <h2>{t.yogasTitle}</h2>

            {yogas.map((y: any, idx: number) => (
                <div className="yoga-entry" key={`yoga-${idx}`}>
                    <span className="yoga-name">{y.name}</span>
                    {Array.isArray(y.significance) ? y.significance.map((p: string, i: number) => <p key={i}>{p}</p>) : <p>{y.significance}</p>}
                </div>
            ))}
        </div>
      )}

      {/* CHAPTER VII: Doshas */}
      {doshas.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} VII</div>
            <h2>{t.doshasTitle}</h2>

            {doshas.map((d: any, idx: number) => (
                <div className="yoga-entry" key={`dosha-${idx}`}>
                    <span className="yoga-name">{d.name}</span>
                    {Array.isArray(d.significance) ? d.significance.map((p: string, i: number) => <p key={i}>{p}</p>) : <p>{d.significance}</p>}
                    {d.remedy && (
                        <p><span style={{fontWeight: "bold", color: "var(--primary-dark)"}}>{t.remedy}</span> {d.remedy}</p>
                    )}
                </div>
            ))}
        </div>
      )}

      {/* CHAPTER VIII: Cycle of Time (Roadmap) */}
      {roadmap.length > 0 && (
        <div className="pdf-page">
            <div className="chapter-num">{t.chapter} VIII</div>
            <h2>{t.cycleOfTime}</h2>
            
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "30px", marginTop: "30px" }}>
                {roadmap.map((m: any, idx: number) => (
                    <div className="timeline-section" key={idx}>
                        <span className="timeline-month">{m.month}</span>
                        <div style={{ marginBottom: "15px", fontSize: "11pt", fontWeight: "bold", 
                            color: m.status === "Excellent" || m.status === "Good" ? "#2f855a" : (m.status === "Challenging" ? "#c53030" : "var(--gold)")
                        }}>
                            {m.status}
                        </div>
                        <p>{m.prediction}</p>
                    </div>
                ))}
            </div>
        </div>
      )}

      {/* CHAPTER IX: Summary */}
      {summaryText && (
          <div className="pdf-page">
            <div className="chapter-num">{t.chapter} IX</div>
            <h2>{t.summary}</h2>
            <p className="first-paragraph">
                <span className="drop-cap">{getFirstLetter(summaryText)}</span>
                {getRestOfText(summaryText)}
            </p>
          </div>
      )}

      {/* END OF READING MARKER */}
      <div className="pdf-page" style={{ justifyContent: "center", alignItems: "center", minHeight: "400px" }}>
          <div className="shloka-block">
              <p className="shloka-text">{prediction.shloka.sanskrit}</p>
              <p style={{ fontSize: "12pt" }}>"{prediction.shloka.meaning}"</p>
          </div>

          {ashirvadaText && (
              <div style={{ marginTop: "40px", textAlign: "center", padding: "0 40px" }}>
                  <div style={{ fontSize: "42pt", color: "var(--gold)", marginBottom: "20px", fontFamily: "'Noto Sans Devanagari', serif", opacity: 0.9 }}>ॐ</div>
                  <h3 style={{ fontSize: "20pt", fontStyle: "italic", marginBottom: "20px", color: "var(--primary-dark)" }}>{t.ashirvadaTitle}</h3>
                  <p style={{ fontSize: "14pt", fontStyle: "italic", textAlign: "center", textIndent: 0, lineHeight: 1.8 }}>
                      "{ashirvadaText}"
                  </p>
              </div>
          )}
          
          <div style={{ textAlign: "center", marginTop: "80px", borderTop: "1px solid var(--gold)", paddingTop: "40px", width: "50%" }}>
              <p style={{ textIndent: 0, fontFamily: "'Cinzel', 'Noto Serif Kannada', serif", letterSpacing: "2px", textTransform: "uppercase", fontSize: "14pt", color: "var(--primary-dark)" }}>
                  {t.endOfReading}
              </p>
          </div>
      </div>

    </div>
  );
};
