/**
 * Baggona Purohita Activity Tracker Service
 * 
 * Provides centralized telemetry and tracking for priests:
 * - Page views per module (with 5s debounce)
 * - Kundalis generated
 * - Consultation questions asked
 * - Profile synchronization & verification
 */

import {
  recordPurohitaActivity,
  getPurohitaProfile,
  savePurohitaProfile,
  type PurohitaActivityDoc,
  type PurohitaProfileDoc
} from "../../db/firestoreDb";
import { getIndianStandardDateStr } from "../../core/placeTime";

// In-memory debounce cache to prevent duplicate rapid page view logs
const recentPageViews = new Map<string, number>();
const DEBOUNCE_PAGE_VIEW_MS = 5000;

/**
 * Standardize Purohita ID to lowercase alphanumeric slug
 */
export function canonicalPurohitaId(rawIdOrName?: string): string {
  const clean = (rawIdOrName || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_")
    .replace(/_+/g, "_");

  if (!clean || clean === "_") return "priest_unknown";
  if (!clean.startsWith("priest_") && !clean.startsWith("pandit_")) {
    return `priest_${clean}`;
  }
  return clean;
}

/**
 * Track a page visit made by a priest
 */
export async function trackPurohitaPageView(
  rawPurohitaId: string,
  priestName: string,
  page: string
): Promise<PurohitaActivityDoc | null> {
  const purohitaId = canonicalPurohitaId(rawPurohitaId);
  const now = Date.now();
  const debounceKey = `${purohitaId}_${page}`;
  const lastTime = recentPageViews.get(debounceKey) || 0;

  if (now - lastTime < DEBOUNCE_PAGE_VIEW_MS) {
    return null; // Debounced
  }
  recentPageViews.set(debounceKey, now);

  const pageLabelMap: Record<string, string> = {
    priestdashboard: "ಪುರೋಹಿತರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ (Priest Dashboard)",
    panchanga: "ದೈನಂದಿನ ಪಂಚಾಂಗ (Daily Panchanga)",
    kundli: "ಜನನ ಕುಂಡಲಿ ರಚನೆ (Janma Kundli)",
    sankhyashastra: "ಸಂಖ್ಯಾಶಾಸ್ತ್ರ ಸಮಾಲೋಚನೆ (Sankhya Shastra)",
    kaaladiksuchi: "ದಿವ್ಯ ಕಾಲ ದಿಕ್ಸೂಚಿ (Kaala Diksuchi)",
    hindinajanma: "ಹಿಂದಿನ ಜನ್ಮ ರಹಸ್ಯ (Purva Janma)",
    vahanamuhurtha: "ವಾಹನ ಖರೀದಿ ಮುಹೂರ್ತ (Vahana Muhurtha)",
    public_kundli: "ಸಾರ್ವಜನಿಕ ಕುಂಡಲಿ ದರ್ಶನ (Public Kundli)",
    settings: "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್ಸ್ (Settings)"
  };

  const friendlyPage = pageLabelMap[page] || page;

  return recordPurohitaActivity({
    purohitaId,
    priestName: priestName || "ಪುರೋಹಿತರು",
    activityType: "page_view",
    page,
    details: `${friendlyPage} ಪುಟವನ್ನು ತೆರೆಯಲಾಗಿದೆ (Opened page)`,
    timestamp: new Date().toISOString(),
    date: getIndianStandardDateStr(new Date())
  });
}

/**
 * Track a Kundli generated by a priest
 */
export async function trackPurohitaKundliGenerated(
  rawPurohitaId: string,
  priestName: string,
  clientName: string,
  details?: string
): Promise<PurohitaActivityDoc> {
  const purohitaId = canonicalPurohitaId(rawPurohitaId);
  return recordPurohitaActivity({
    purohitaId,
    priestName: priestName || "ಪುರೋಹಿತರು",
    activityType: "kundli_generated",
    page: "kundli",
    details: `ಜಾತಕ ರಚಿಸಲಾಗಿದೆ: ${clientName || "ಭಕ್ತರು"} ${details ? `(${details})` : ""}`.trim(),
    metadata: { clientName },
    timestamp: new Date().toISOString(),
    date: getIndianStandardDateStr(new Date())
  });
}

/**
 * Track a question asked or reading requested by a priest
 */
export async function trackPurohitaQuestionAsked(
  rawPurohitaId: string,
  priestName: string,
  questionOrCategory: string,
  categoryOrQuestion?: string
): Promise<PurohitaActivityDoc> {
  const purohitaId = canonicalPurohitaId(rawPurohitaId);
  const isArg3Cat = ["sankhyashastra", "kundli", "panchanga", "kaaladiksuchi", "hindinajanma"].includes(
    (questionOrCategory || "").toLowerCase()
  );
  const question = isArg3Cat && categoryOrQuestion ? categoryOrQuestion : questionOrCategory;
  const category = isArg3Cat ? questionOrCategory : (categoryOrQuestion || "priestdashboard");

  return recordPurohitaActivity({
    purohitaId,
    priestName: priestName || "ಪುರೋಹಿತರು",
    activityType: "question_asked",
    page: category.toLowerCase().includes("sankhya") ? "sankhyashastra" : category,
    details: `ಪ್ರಶ್ನೆ ಕೇಳಲಾಗಿದೆ: "${question.slice(0, 80)}${question.length > 80 ? "..." : ""}"`,
    metadata: { question, category },
    timestamp: new Date().toISOString(),
    date: getIndianStandardDateStr(new Date())
  });
}

/**
 * Ensure Purohita Profile exists in the database.
 * If not present, creates it with initial values.
 * Accepts either a parameters object or positional arguments.
 */
export async function ensurePurohitaProfile(
  paramsOrId: string | {
    purohitaId: string;
    priestName: string;
    mobileNumber?: string;
    email?: string;
    allowedModules?: string[];
  },
  priestNameArg?: string,
  mobileNumberArg?: string,
  emailArg?: string
): Promise<PurohitaProfileDoc> {
  const params = typeof paramsOrId === "string"
    ? {
        purohitaId: paramsOrId,
        priestName: priestNameArg || "ಶ್ರೀರಾಮ್ ಪಂಡಿತ್",
        mobileNumber: mobileNumberArg || "",
        email: emailArg || ""
      }
    : paramsOrId;

  const purohitaId = canonicalPurohitaId(params.purohitaId);
  const existing = await getPurohitaProfile(purohitaId);

  if (existing) {
    // If new mobile or email is provided and previously missing, update it
    let needsUpdate = false;
    const updates: Partial<PurohitaProfileDoc> = { purohitaId };

    if (params.mobileNumber && !existing.mobileNumber) {
      updates.mobileNumber = params.mobileNumber;
      updates.phone = params.mobileNumber;
      needsUpdate = true;
    }
    if (params.email && !existing.email) {
      updates.email = params.email;
      needsUpdate = true;
    }
    if (params.priestName && (!existing.priestName || existing.priestName === "ಪುರೋಹಿತರು")) {
      updates.priestName = params.priestName;
      needsUpdate = true;
    }

    if (needsUpdate) {
      return savePurohitaProfile(updates as any);
    }
    return existing;
  }

  // Create new official profile
  return savePurohitaProfile({
    purohitaId,
    priestName: params.priestName || "ಶ್ರೀರಾಮ್ ಪಂಡಿತ್",
    mobileNumber: params.mobileNumber || "",
    email: params.email || "",
    coinBalance: 0,
    allowedModules: params.allowedModules || ["panchanga", "sankhyashastra", "diksuchi", "purva_janma"],
    status: "active",
    registeredAt: new Date().toISOString(),
    lastActiveAt: new Date().toISOString()
  });
}
